# Generated by Django 3.0.3 on 2020-02-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='tag',
            field=models.CharField(choices=[(0, 'Fan Panel'), (1, 'Special Guest Panel'), (2, 'Performance'), (3, 'Anime Screening'), (4, 'Cosplay'), (5, '18+ (ID Required)'), (6, 'Video Gaming'), (7, 'Autographs')], max_length=75, unique=True),
        ),
    ]
