# Generated by Django 3.0.3 on 2020-02-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200207_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='tag',
            field=models.CharField(choices=[('fanpanel', 'Fan Panel'), ('guestpanel', 'Special Guest Panel'), ('performance', 'Performance'), ('screening', 'Anime Screening'), ('cosplay', 'Cosplay'), ('18+', '18+ (ID Required)'), ('gaming', 'Video Gaming'), ('autographs', 'Autographs')], max_length=75, unique=True),
        ),
    ]
