# Generated by Django 3.0.3 on 2020-02-07 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_auto_20200207_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='hosted_events',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
