# Generated by Django 3.0.3 on 2020-03-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20200303_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remark',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
