# Generated by Django 3.0.3 on 2020-03-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_event_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_speakers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
